[package]
name = "vnoi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmoj = "0.1.5"

[workspace]
members = [
]
