#!/bin/bash

# exit on error
set -e

# Import
source ./setup

help() {
  cat <<EOF
  Usage:
    clean --rs|zig|py --cf|dm <problem>

  Options:
    -r, --rs    Rust source
    -z, --zig   Zig source
    -c, --cpp   C++ source
        --c     C source
    -p, --py    Python source

    --cf        Codeforces
    --dm        DMOJ based (VNOI, DMOJ)

    -h, --help  Display help message

EOF
}

clean_rust() {
  if ! [ -f ${META[0]}/Cargo.toml ]; then
    $CARGO clean
  else
    echo "No code"
  fi
}

clean_zig() {
  echo "TODO"
}

clean_cpp() {
  echo "TODO"
}

clean_c() {
  echo "TODO"
}

clean_python() {
  echo "TODO"
}

clean_code() {
  if [ ${#META[@]} -ne 0 ]; then
    cd ${META[0]}
  fi

  case $LANGUAGE in
  $RUST_LANG)
    clean_rust $ARGS
    ;;
  $ZIG_LANG)
    clean_zig $ARGS
    ;;
  $CPP_LANG)
    clean_cpp $ARGS
    ;;
  $C_LANG)
    clean_c $ARGS
    ;;
  $PYTHON_LANG)
    clean_python $ARGS
    ;;
  *)
    help
    ;;
  esac
}

clean_code
