#!/bin/bash

# exit on error
set -e

# Import
source ./setup

ZED_EDITOR="zed"

help() {
	cat <<EOF
  Usage:
    open --rs|zig|py --cf|dm <problem_id>

EOF
	help_options
}

open_rust() {
  $ZED_EDITOR .
}

open_zig() {
  $ZED_EDITOR .
}

open_cpp() {
  $ZED_EDITOR .
}

open_c() {
  $ZED_EDITOR .
}

open_python() {
  $ZED_EDITOR .
}

open_code() {
	if [ "$HELP_FLAG" = true ]; then
		help
		exit 1
	fi

	if [ ${#META[@]} -ne 0 ]; then
		cd ${META[0]}
	fi

	case $LANGUAGE in
	$RUST_LANG)
		open_rust $ARGS
		;;
	$ZIG_LANG)
		open_zig $ARGS
		;;
	$CPP_LANG)
		open_cpp $ARGS
		;;
	$C_LANG)
		open_c $ARGS
		;;
	$PYTHON_LANG)
		open_python $ARGS
		;;
	*)
		help
		;;
	esac
}

open_code
