#!/bin/bash

# Source
DMOJ="dmoj-site"
VNOI=""
RUST_SRC="."
ZIG_SRC="zig"
C_SRC="c"
CPP_SRC="cpp"
PYTHON_SRC="python"

# Compiler
CARGO="cargo"
ZIG="zig"
CC="gcc"
CPP="g++"
PYTHON="python"
PYTHON3="python3"

help() {
  cat <<EOF
  Usage:
    run --rs|zig|py <problem_id>

  Options:
    -r, --rs    Rust source
    -z, --zig   Zig source
    -c, --cpp   C++ source
        --c     C source
    -p, --py    Python source
    -h, --help  Display help message
EOF
}

dmoj() {
  $CARGO run -p $DMOJ --bin $@
}

vnoi() {
  $CARGO run --bin $@
}

run_rust() {
  $CARGO run --bin $@
}

run_zig() {
  cd $ZIG_SRC
  $ZIG build run -Dproblem=$@
}

run_cpp() {
  cd CPP_SRC$
  $CPP $@.cpp
}

run_c() {
  cd C_SRC$
  $CC $@.c
}

run_python() {
  cd $PYTHON_SRC
  $PYTHON3 $@.py
}

case "$1" in
--rs | -r)
  run_rust ${@:2}
  ;;
--zig | -z)
  run_zig ${@:2}
  ;;
--cpp | -c)
  run_cpp ${@:2}
  ;;
--c)
  run_c ${@:2}
  ;;
--py | -p)
  run_python ${@:2}
  ;;
*)
  help
  ;;
esac
