#!/bin/bash

# exit on error
set -e

# Import
source ./setup

help() {
	cat <<EOF
  Usage:
    run --rs|zig|py --cf|dm <problem_id>

EOF
	help_options
}

run_rust() {
	$CARGO run --bin $@
}

run_zig() {
	$ZIG build run -Dproblem=$@
}

run_cpp() {
	$CPP -g $2.cpp
	echo "Complication successful"
	./a.out
}

run_c() {
	$CC -g $2.c
	echo "Complication successful"
	./a.out
}

run_python() {
	$PYTHON3 $@.py
}

run_code() {
	if [ "$HELP_FLAG" = true ]; then
		help
		exit 1
	fi

	if [ ${#META[@]} -ne 0 ]; then
		cd ${META[0]}
	fi

	case $LANGUAGE in
	$RUST_LANG)
		run_rust $ARGS
		;;
	$ZIG_LANG)
		run_zig $ARGS
		;;
	$CPP_LANG)
		run_cpp $ARGS
		;;
	$C_LANG)
		run_c $ARGS
		;;
	$PYTHON_LANG)
		run_python $ARGS
		;;
	*)
		help
		;;
	esac
}

run_code
