#!/bin/bash

DMOJ="dmoj-site"
VNOI=""
RUST_SRC="."
ZIG_SRC="zig"
PYTHON_SRC="python"

CARGO="cargo"
ZIG="zig"
PYTHON="python"
PYTHON3="python3"

help() {
  cat <<EOF
  Usage:
    run --rs|zig|py <problem_id>

  Options:
    -r, --rs    Rust lang source
    -z, --zig   Zig lang source
    -p, --py    Python lang source
    -h, --help  Display help message
EOF
}

dmoj() {
  $CARGO run -p $DMOJ --bin $@
}

vnoi() {
  $CARGO run --bin $@
}

run_rust() {
  $CARGO run --bin $@
}

run_zig() {
  cd $ZIG_SRC
  $ZIG build run -Dproblem=$@
}

run_python() {
  cd $PYTHON_SRC
  $PYTHON3 $@.py
}

case "$1" in
--rs | -r)
  run_rust ${@:2}
  ;;
--zig | -z)
  run_zig ${@:2}
  ;;
--py | -p)
  run_python ${@:2}
  ;;
*)
  help
  ;;
esac
